name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install SBCL
        run: |
          sudo apt-get update
          sudo apt-get install -y sbcl

      - name: Install Quicklisp
        run: |
          curl -O https://beta.quicklisp.org/quicklisp.lisp
          sbcl --non-interactive \
               --load quicklisp.lisp \
               --eval "(quicklisp-quickstart:install)" \
               --eval "(ql:add-to-init-file)" \
               --quit

      - name: Run tests
        run: |
          sbcl --non-interactive \
               --eval "(require :asdf)" \
               --eval "(asdf:test-system :normal)" \
               --quit

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: lisp-test-report
          path: |
            **/normal/tests/**/*.fasl
            **/normal/tests/**/*.lisp
