name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install SBCL
        run: sudo apt-get update && sudo apt-get install -y sbcl curl

      - name: Install Quicklisp
        run: |
          curl -O https://beta.quicklisp.org/quicklisp.lisp
          sbcl --non-interactive \
               --load quicklisp.lisp \
               --eval '(quicklisp-quickstart:install :path "~/.quicklisp")' \
               --quit
          echo '(load (merge-pathnames "setup.lisp" (user-homedir-pathname ".quicklisp/")))' >> ~/.sbclrc

      - name: Link project into Quicklisp local-projects
        run: |
          mkdir -p ~/.quicklisp/local-projects
          ln -s $GITHUB_WORKSPACE ~/.quicklisp/local-projects/normal

      - name: Run tests
        run: |
          sbcl --non-interactive \
               --eval "(require :asdf)" \
               --eval "(ql:quickload :normal)" \
               --eval "(asdf:test-system :normal)" \
               --quit | tee test-report.txt

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test-report.txt
