name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install SBCL
        run: |
          sudo apt-get update
          sudo apt-get install -y sbcl curl

      - name: Install Quicklisp
        run: |
          curl -O https://beta.quicklisp.org/quicklisp.lisp
          sbcl --non-interactive \
               --load quicklisp.lisp \
               --eval "(quicklisp-quickstart:install)" \
               --quit
          echo "(load (merge-pathnames \"quicklisp/setup.lisp\" (user-homedir-pathname)))" >> ~/.sbclrc

      - name: Run tests
        run: |
          mkdir -p ~/quicklisp/local-projects
          ln -s $GITHUB_WORKSPACE ~/quicklisp/local-projects/normal
          sbcl --non-interactive \
               --eval "(require :asdf)" \
               --eval "(asdf:test-system :normal)" \
               --quit | tee test-report.txt

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lisp-test-report
          path: test-report.txt
