name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl bzip2 make gcc sbcl

      - name: Install SBCL (2.3.6 prebuilt)
        run: |
            curl -L https://downloads.sourceforge.net/project/sbcl/sbcl/2.3.6/sbcl-2.3.6-x86-64-linux-binary.tar.bz2 -o sbcl-bin.tar.bz2
            tar xjf sbcl-bin.tar.bz2
            cd sbcl-2.3.6-x86-64-linux
            sudo sh install.sh

      - name: Install Quicklisp
        run: |
          curl -O https://beta.quicklisp.org/quicklisp.lisp
          sbcl --non-interactive \
            --load quicklisp.lisp \
            --eval '(quicklisp-quickstart:install)' \
            --quit

      - name: Link project into Quicklisp local-projects
        run: |
          mkdir -p ~/quicklisp/local-projects
          ln -s $GITHUB_WORKSPACE ~/quicklisp/local-projects/normal

      - name: Run tests
        run: |
          mkdir -p logs
          sbcl --non-interactive --load ci-tests.lisp > logs/test-output.log 2>&1 || true

      - name: Upload test logs
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: logs/test-output.log
