name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install SBCL
        run: sudo apt-get update && sudo apt-get install -y sbcl curl

      - name: Install Quicklisp
        run: |
          curl -O https://beta.quicklisp.org/quicklisp.lisp
          sbcl --non-interactive \
               --load quicklisp.lisp \
               --eval '(quicklisp-quickstart:install)' \
               --quit

      - name: Symlink project into Quicklisp local-projects
        run: |
          mkdir -p ~/quicklisp/local-projects
          ln -s $GITHUB_WORKSPACE ~/quicklisp/local-projects/normal

      - name: Run tests
        run: |
          sbcl --non-interactive \
               --load ~/quicklisp/setup.lisp \
               --eval "(ql:quickload :normal)" \
               --eval "(asdf:test-system :normal)" \
               --quit > test-report.txt 2>&1

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test-report.txt
